name = "chocante-dynamic-cache"
main = "worker.js"
compatibility_date = "2026-04-06"
workers_dev = false
preview_urls = false
keep_vars = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

[observability.traces]
enabled = false
head_sampling_rate = 1
